name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          ignore: DL3008 DL3059
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          IMAGE_NAME=lennartjuetteunic/sapcommerce-azuredevops-ci-image
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TS
          docker push $IMAGE_NAME:$TS
          docker push $IMAGE_NAME:latest

